**Challenge 1** : Création et exploration d’un DataFrame

**Objectif** : Créer un DataFrame simple et explorer sa structure.

**Travail à faire** :

Crée un DataFrame avec 3 colonnes : Nom, Âge, Ville.

Liste des données: data=[\
                                                                   ["Amine", 28, "Casablanca"],
                                                                   ["Lina", 22, "Rabat"],
                                                                   ["Youssef", 35, "Fès"],
                                                                   ["Salma", 30, "Casablanca"],
                                                                   ["Nora", np.nan, "Tanger"]]
Affiche les 5 premières lignes avec head().
Affiche la structure du DataFrame avec info().

Affiche des statistiques descriptives avec describe().

In [11]:
import pandas as pd
import numpy as np

data = [ ["Amine", 28, "Casablanca"],["Lina", 22, "Rabat"],["Youssef", 35, "Fès"],["Salma", 30, "Casablanca"], ["Nora", np.nan, "Tanger"] ]

df = pd.DataFrame(data, columns=["Nom", "Age", "Ville"])
df.head()
df.info()
df.describe()

             Age
count   4.000000
mean   28.750000
std     5.377422
min    22.000000
25%    26.500000
50%    29.000000
75%    31.250000
max    35.000000

**Challenge 2** : Sélection et filtrage de données
**Objectif** : Savoir sélectionner des colonnes/lignes et filtrer selon des conditions.

**Travail à faire **:

Sélectionne la colonne Ville du DataFrame.

Affiche toutes les lignes où l’Âge est supérieur à 25.

Affiche le nom et la ville des personnes de Casablanca.

In [24]:
ageColumn = df[["Age"]]

ageColumnFiltered = df[df["Age"]>25]

print(ageColumnFiltered)

cityFiltered = df[df["Ville"] == "Casablanca" ][["Age", "Ville"]]
print(cityFiltered)

       Nom   Age       Ville  Année de Naissance
0    Amine  28.0  Casablanca              1997.0
2  Youssef  35.0         Fès              1990.0
3    Salma  30.0  Casablanca              1995.0
    Age       Ville
0  28.0  Casablanca
3  30.0  Casablanca

       Nom   Age Localisation  Année de Naissance
0    AMINE  28.0   Casablanca              1997.0
1     LINA  22.0        Rabat              2003.0
2  YOUSSEF  35.0          Fès              1990.0
3    SALMA  30.0   Casablanca              1995.0
4     NORA   NaN       Tanger                 NaN

**Challenge 3** : Ajout et modification de colonnes

**Objectif **: Manipuler les colonnes du DataFrame.

**Travail à faire** :

Ajoute une colonne Année de Naissance = 2025 - Âge.

Modifie les noms en majuscules avec .str.upper().

Renomme la colonne Ville en Localisation.

In [27]:


df["Année de Naissance"] = 2025 - df["Age"]

df["Nom"] = df["Nom"].str.upper()

df.rename(columns={'Ville': 'Localisation'})

     Nom    Age  Ville  Année de Naissance
0  False  False  False               False
1  False  False  False               False
2  False  False  False               False
3  False  False  False               False
4  False  False  False                True
       Nom    Age       Ville  Année de Naissance
0    AMINE  28.00  Casablanca             1997.00
1     LINA  22.00       Rabat             2003.00
2  YOUSSEF  35.00         Fès             1990.00
3    SALMA  30.00  Casablanca             1995.00
4     NORA  28.75      Tanger             1996.25

**Challenge 4** : Gestion des valeurs manquantes
**Objectif** : Identifier et traiter les valeurs manquantes.

**Travail à faire** :

Introduis manuellement une valeur NaN dans la colonne Âge.

Affiche les lignes contenant des valeurs manquantes avec isnull().

Remplace les valeurs manquantes par la moyenne des âges avec fillna().

In [ ]:
print(df.isnull())

df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Année de Naissance"] = 2025 - df["Age"]

print(df)

**Challenge 5** : Tri et suppression
**Objectif** : Trier un DataFrame et supprimer des lignes ou colonnes.

**Travail à faire :**

Trie les lignes par âge décroissant avec sort_values(by='Âge', ascending=False).

Supprime la colonne Année de Naissance avec drop().

Supprime la première ligne du DataFrame avec drop(index=0).

In [30]:
df = df.sort_values(by="Age", ascending=False)

In [31]:
print(df)

       Nom    Age       Ville  Année de Naissance
2  YOUSSEF  35.00         Fès             1990.00
3    SALMA  30.00  Casablanca             1995.00
4     NORA  28.75      Tanger             1996.25
0    AMINE  28.00  Casablanca             1997.00
1     LINA  22.00       Rabat             2003.00

In [32]:

df = df.drop(columns=["Année de Naissance"])
df = df.drop(index=df.index[0])

print(df)

     Nom    Age       Ville
3  SALMA  30.00  Casablanca
4   NORA  28.75      Tanger
0  AMINE  28.00  Casablanca
1   LINA  22.00       Rabat